# **Import All Dataset and Liberies**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
amazon_dataset = pd.read_csv('/content/amazon_cells_labelled.txt', sep='\t', header = None)
yelp_dataset = pd.read_csv('/content/yelp_labelled.txt', sep='\t', header = None)
imdb_dataset = pd.read_csv('/content/imdb_labelled.txt', sep='\t', header = None)

In [3]:
amazon_dataset.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [4]:
yelp_dataset.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [5]:
imdb_dataset.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

**See All Dataset Shape**

In [6]:
yelp_dataset.shape

(1000, 2)

In [7]:
amazon_dataset.shape

(1000, 2)

In [8]:
imdb_dataset.shape

(748, 2)

**Check All Dataset Null value**

In [9]:
yelp_dataset.isnull().sum()

0    0
1    0
dtype: int64

In [10]:
amazon_dataset.isnull().sum()

0    0
1    0
dtype: int64

In [11]:
imdb_dataset.isnull().sum()

0    0
1    0
dtype: int64

**Describe All Dataset**

In [12]:
amazon_dataset.describe()

1
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [13]:
yelp_dataset.describe()

1
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [14]:
imdb_dataset.describe()

1
count  748.000000
mean     0.516043
std      0.500077
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

**Define All Dataset Columns Name**

In [15]:
columns_name = ['Reviews','Sentiments']

In [16]:
amazon_dataset.columns = columns_name
amazon_dataset.head()

Reviews  Sentiments
0  So there is no way for me to plug it in here i...           0
1                        Good case, Excellent value.           1
2                             Great for the jawbone.           1
3  Tied to charger for conversations lasting more...           0
4                                  The mic is great.           1

In [17]:
yelp_dataset.columns = columns_name
yelp_dataset.head()

Reviews  Sentiments
0                           Wow... Loved this place.           1
1                                 Crust is not good.           0
2          Not tasty and the texture was just nasty.           0
3  Stopped by during the late May bank holiday of...           1
4  The selection on the menu was great and so wer...           1

In [18]:
imdb_dataset.columns = columns_name
imdb_dataset.head()

Reviews  Sentiments
0  A very, very, very slow-moving, aimless movie ...           0
1  Not sure who was more lost - the flat characte...           0
2  Attempting artiness with black & white and cle...           0
3       Very little music or anything to speak of.             0
4  The best scene in the movie was when Gerardo i...           1

**Append All Datasets**

In [19]:
dataset = amazon_dataset.append([yelp_dataset, imdb_dataset], ignore_index=True)

In [20]:
dataset.head()

Reviews  Sentiments
0  So there is no way for me to plug it in here i...           0
1                        Good case, Excellent value.           1
2                             Great for the jawbone.           1
3  Tied to charger for conversations lasting more...           0
4                                  The mic is great.           1

In [21]:
dataset.shape

(2748, 2)

**Distribution the Sentiments**

In [22]:
dataset['Sentiments'].value_counts()

1    1386
0    1362
Name: Sentiments, dtype: int64

**Divide Input and Output Dataset**

In [23]:
X = dataset['Reviews']
Y = dataset['Sentiments']

**Data Cleaning**
# ( Remove stopwords, punctuations, regular expression and use lemmatization )

In [24]:
import string
from spacy.lang.en.stop_words import STOP_WORDS

**List of punctuation**

In [25]:
punc = string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

**List of stop words**

In [26]:
stopwords = list(STOP_WORDS)
stopwords

['by',
 'done',
 'without',
 'between',
 'behind',
 'well',
 'whose',
 'us',
 'whatever',
 'these',
 'rather',
 'anywhere',
 'as',
 'anything',
 'get',
 'ours',
 '‘d',
 'sometime',
 'twelve',
 "'ve",
 'sometimes',
 'thus',
 'wherever',
 'our',
 '‘m',
 'seem',
 'five',
 '‘ve',
 'everything',
 "'re",
 'at',
 'whereby',
 'had',
 'both',
 'very',
 'please',
 'nothing',
 'amongst',
 '’d',
 'so',
 'hundred',
 'such',
 'am',
 'less',
 'whom',
 'once',
 'ever',
 'the',
 'ourselves',
 'least',
 'because',
 'beyond',
 'part',
 'show',
 "'s",
 '’ve',
 'becomes',
 'across',
 'herein',
 'again',
 'serious',
 'been',
 'nobody',
 'whereafter',
 'whereas',
 'you',
 'their',
 'her',
 'thereupon',
 'became',
 'any',
 'we',
 'last',
 'see',
 'quite',
 'noone',
 'can',
 'not',
 'herself',
 'neither',
 'thru',
 'n’t',
 'empty',
 'three',
 'against',
 'since',
 'various',
 'a',
 'however',
 'yours',
 'formerly',
 'if',
 'what',
 'eleven',
 'everyone',
 'off',
 'side',
 'whole',
 'for',
 'some',
 'in',
 'bei

**Data cleaning** ( Remove stopwords, punctuations )

In [27]:
# if root word is not pronoun that going to convert lower form
# if word is proper noun, directly taking lower form
import spacy
nlp = spacy.load('en_core_web_sm')

def data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = []
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
  
  tokens_clean = []
  for token in tokens:
    if token not in stopwords and token not in punc:
      tokens_clean.append(token)
  return tokens_clean

In [28]:
# check remove stopwords and punctuations from text
data_cleaning("Hi I'm jack, From kaptai rangamati. Are you excited to join with me?")

['hi', 'jack', 'kaptai', 'rangamati', 'excited', 'join']

Feature Engineering Vectorization ( TF_IDF )

In [29]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [30]:
tfidf = TfidfVectorizer(tokenizer = data_cleaning)

In [31]:
classifier = LinearSVC()

# Model Train

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [33]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                      horrible, had to switch 3 times.
1509                             Thoroughly disappointed!
144     The phone takes FOREVER to charge like 2 to 5 ...
2483    The film gives meaning to the phrase, "Never i...
Name: Reviews, dtype: object

In [34]:
x_train.shape

(2198,)

In [35]:
x_test.shape

(550,)

**Fit data**

In [36]:
clf = Pipeline([('tfidf',tfidf), ('clf',classifier)])

In [37]:
clf.fit(x_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function data_cleaning at 0x7f144e923a70>)),
                ('clf', LinearSVC())])

# Predict Data

In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [39]:
y_pred = clf.predict(x_test)

In [40]:
confusion_matrix(y_test, y_pred)

array([[211,  59],
       [ 57, 223]])

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.78      0.78       270
           1       0.79      0.80      0.79       280

    accuracy                           0.79       550
   macro avg       0.79      0.79      0.79       550
weighted avg       0.79      0.79      0.79       550



In [42]:
accuracy_score(y_test, y_pred)

0.7890909090909091

In [43]:
clf.predict(["The mic is great.	"])

array([1])

In [44]:
clf.predict(["Very little music or anything to speak of."])

array([0])